### ISSUE TITLE
charybdis.io doesn't work without the www.

### ISSUE THREAD

**Issue by Mikaela** [charybdis-ircd/charybdis-ircd.github.io#1]
The solution would be to change `CNAME` to `charybdis.io` (as GitHub automatically handles `www.<cname>` and following [Configuring an A record with your DNS provider](https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/#configuring-an-a-record-with-your-dns-provider).

`www.charybdis.io` could stay as CNAME to `charybdis-ircd.github.io`.

Alternatively there could be some server on charybdis.io redirecting to www.charybdis.io like with ircv3.org.

**Comment by kaniini** [comment]
This is done.
